############################
## HUGO MODULES
############################

# imports:
#   - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

# Mount local content to Hugo's content directory
mounts:
  - source: content
    target: content
  - source: layouts
    target: layouts
  - source: assets
    target: assets
  - source: static
    target: static
